52 webpack and folder set up
FEC5/web-application-X pull request #4
Opened 2022-08-24 23:23 UTC by qzyan

[trello ticket](https://trello.com/c/hFjLbQv5/52-webpack-and-folder-set-up-s)  
- webpack set up 
- .gitignore set up  
- client/src/components set up

2022-08-24 23:29 UTC, hepnerthomas commented on webpack.config.js
> +  module: {
add `devServer` to the module if you want webpack to serve the files locally.

2022-08-24 23:30 UTC, hepnerthomas commented on webpack.config.js
> +  module: {
https://webpack.js.org/configuration/dev-server/

2022-08-24 23:31 UTC, hepnerthomas requested changes
Great work, just one minor change requested!

**Requested Changes**
- add example.env file w/ comments about how to create an .env file

2022-08-24 23:56 UTC, allanviguilla commented
@qzyan also just wanted to ask to include eslint as a dependency in package.json

2022-08-25 00:03 UTC, hepnerthomas commented on exmple.env
> +API_TOKEN
@qzyan Can you change the filename to `example.env` really quick?

2022-08-25 00:03 UTC, hepnerthomas commented on package.json
> +    "dotenv": "^16.0.1",
@qzyan nicely done!

2022-08-25 00:08 UTC, hepnerthomas approved these changes
All good - thank you for adding in the example.env file!

2022-08-25 00:09 UTC, merged